// <auto-generated />
namespace PLE444.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class course_approval : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(course_approval));
        
        string IMigrationMetadata.Id
        {
            get { return "201702102127357_course_approval"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
